# Data Science - Python Intro

## Installatie

Om Python en Jupyter Notebook te installeren volg je [deze link](https://www.anaconda.com/products/individual#windows).
Anaconda is een bundle met Python en een groot aantal extra packages die vaak gebruikt worden bij Data Science en Machine Learning.
Download de executable en installeer het.
Hierbij mogen de default opties gekozen worden.

Ook al heeft Anaconda zijn eigen package manager (conda), niet alle packages kunnen door deze correct gevonden worden. Daarom moet je ook nog pip installeren door middel van onderstaande commando.

Dit is bijgetypt als voorbeeld

In [1]:
!conda install pip

^C


Clone nu de github repo waar deze file in staat. Deze kan gevonden worden via [de link, pas dit aan naar de repo van dit jaar](TODO).
Open nu een commandprompt (cmd.exe) en navigeer met behulp van cd naar de folder waar je de repo geplaatst hebt.
Voer op die plaats het commando **jupyter notebook** uit.
Dit opent een webpagina met de inhoud van je folder waar je zat.
Open nu het notebook dat we hier gebruiken (Deze file noemt **03_PythonIntro**).

Op dit punt zou je hetzelfde moeten zien als hier staat.

## Jupyter notebook

Jupyter notebook maakt het mogelijk om hier zowel de opgave, uitleg als code te tonen en uit te voeren.
Hiervoor wordt er gebruik gemaakt van cellen.
Ook is het mogelijk om zowel code als tekstuele vragen te stellen.

Een korte intro over jupyter notebook kan je [hier](https://realpython.com/jupyter-notebook-introduction/) lezen.
In grote lijnen wordt er gewerkt met cellen. Het type van de cel bepaalt of het python-code of plain text (markdown) bevat.
Cellen worden automatisch toegevoegd na het uitvoeren van de laatste cel maar je kan ook er manueel toevoegen onder het menu-item insert of door gebruik te maken van de knoppen "a" en "b" (Hierbij moet je wel eerst uit de cell gaan door middel van Esc). Met deze laatste methode kan je op de gewenste plaats cellen gaan toevoegen.

Uitvoeren van een code cel zorgt ervoor dat de python code die in die cell staat uitgevoerd wordt. In het geval van een markdown cell wordt de tekst gerendered.
Om 1 cell uit te voeren is "shift+enter" de gemakkeljkste methode omdat dan de onderstaande cell automatisch geselecteerd wordt. Deze manier wordt ook gebruikt bij het pijltje met de tekst "Run" bovenaan.
Andere methoden kan je vinden onder het menu "Cell" waarbij je bijvoorbeeld ook van boven naar beneden alle cellen kan laten uitvoeren.
Als je ooit in een situatie zit waar je een endless loop gemaakt hebt of je code lijkt vast te zitten, kan je onder kernel een aantal manieren vinden om het uitvoeren te stoppen. 
Merk op dat als je de kernel stopt, je dan ook alle variabelen en objecten kwijt bent en je opnieuw de code vanin het begin moet uitvoeren.

**Let op:** Bij het pushen naar github van de code is het aangeraden om de output te verwijderen die je hebt gegenereerd.
Dit kan de bestandsgrootte sterk reduceren en vermijdt conflicten. 
Hierbij is het dan wel nodig om ervoor te zorgen dat je code van boven naar beneden kan uitgevoerd worden (met de knop run-all).

## Python intro

Python is een open-source programmeertaal ontwikkeld en ontworpen begin jaren 90. 
Net zoals C# is het een object-georienteerde programmeertaal waarin gebruik gemaakt wordt van klassen en objecten voor structuur aan te brengen in je code. 
Het doel van Python is om een zeer leesbare programmeertaal te zijn en code lijkt sterk op pseudocode. 
In dit vak werken we met Python versie 3.x. 
De syntax vanaf versie 3 is licht afwijkend met die van Python versie 2.x.

Het grootste verschil met C# is dat Python een scripting taal is die gebruik maakt van een interpreter in plaats van een compiler. Dit houdt in dat er geen compile/build step is. Een file of een tekst met Python code wordt door de interpreter ingelezen en lijn voor lijn uitgevoerd.

Python code kan
 * Rechtstreeks in de commandline uitgevoerd worden. Voer hiervoor het commando "python" uit. Dit start de interpreter waar er berekeningen kunnen uitgevoerd worden.
 * Je kan een file aanmaken waar dezelfde lijnen in staan. Wanneer je nu navigeert naar je directory in commandline en daar het commando "python **filename**.py" uitvoert, dan krijg je hetzelfde resultaat. Merk op dat files met python code standaard de extensie .py hebben maar dat dit niet strikt noodzakelijk is.
 * Daarnaast kan je net hetzelfde doen in een cell van jupyter notebook

In [8]:
a = 5
b = 7 

c = a+b
print(c)
# Dit is een commentaar lijn
# Dit is een andere lijn
#
#

12


De grootste verschillen met C# zijn:
* Een scripting taal dus geen compileer stap nodig (het kan wel gedaan worden voor de snelheid van het programma te verbeteren)
* Dynamisch typecasting dus moet niet steeds het type meegegeven worden bij het aanmaken van variabele, definieren van functies en klassen
* Indentation ipv van accolades voor code blocks

Nu ga ik een hele reeks zaken overlopen om de basis van python te leren kennen. 
Merk op dat in de loop van dit vak we python gaan gebruiken op een vereenvoudigde manier dus is het niet nodig om alle details te kennen van hoe python werkt.

In [64]:
# aanmaken van een floating point
a = 6.3
b = -5.2
a-b

# aanmaken van een string
a = int("5")
b = int('7')
a+b
len("dit is een lange string!")

# aanmaken van een list (meerdere types combineren kan maar is niet vaak gewenst)
lijstje = [0,1,2,3,"4",5,"6",7,True,9]
lijstje[2]
lijstje[-2]
lijstje[3:5]
#lijstje[begin:end:step]
lijstje[1:-1:2]

# aanmaken tuple
i, naam = (0, "Jens")
print(i)
print(naam)

# aanmaken dictionary
dictionary = {"0": "Naam", 1:"naam", 3:"test"}
dictionary["Jens"]="value"
print(dictionary)

# output (concatenate of multiple arguments of f-strings f'adfafd {geen string object} afdaf' )
print(i,naam,dictionary, sep=" , ")
print(f'test test {dictionary} test')

# input
#input()

# set string om naar int of omgekeerd
str(a)

# aanmaken functie (default args)
def functienaam(a= 2, b = 1):
    return a+b

functienaam(b=6)

# if-test
if a > b:
    pass
elif a < b:
    pass
else:
    pass

# for loop
#for iterator in range(20):
#    print(iterator)

# while loop
while a < b:
    break
    
# insert in lijst
#lijstje.append(20)
#lijstje.extend(range(10))
lijstje.insert(1, "a")
lijstje

# lijst concatenation

lijstje + lijstje

# classe aanmaken
class Person:
    age=0
    
    def __init__(self, name, age=0, adress="a"):
        self.naam = name
        self.age = age
        self.leeftijd = age
        self.adress = adress
        
persoon = Person("test1", 5)
persoon2 = Person("test2", 10)

print(persoon.age, persoon2.age)

# Inheritance

0
Jens
{'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'}
0 , Jens , {'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'}
test test {'0': 'Naam', 1: 'naam', 3: 'test', 'Jens': 'value'} test
5 10


### Oefening

* Maak een klasse Persoon aan, die minstens een naam en leeftijd en adres heeft.
* Maak een klasse Student aan die hiervan over erft die ook nog een dictionary bijhoudt met welke scores de student had voor welk vak. 
* Maak functies in deze klassen aan om scores toe te voegen, te tellen voor hoeveel vakken de student erdoor is en zijn gemiddelde te berekenen
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt hoeveel studenten er door zijn.
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt voor elk vak hoeveel studenten er door zijn.

In [3]:
# Oefening 1: Persoon
class Person:
    def __init__(self, name, age, adress):
        self.name = name
        self.age = age
        self.adress = adress
p = Person("John Doe", 19, "Gent")
print(p)

In [17]:
# Oefening 2: Student
class Student(Person):
    def __init__(self, name, leeftijd, adres):
        # will take the constructor of the parent class
        super().__init__(name, leeftijd, adres)
        self.scores = {}
        
    # punten toevoegen
    def add_score(self, vak, punt):
        self.scores[vak] = punt
    def aantal_vakken_geslaagd(self):
        aantal = 0
        for vak in self.scores:
            if self.scores[vak] >= 0:
                aantal += 1
        return aantal
    def bereken_gemiddelde(self):
        if len(self.scores) == 0:
            return 0
        gem = 0
        aantal = 0
        for vak in self.scores:
            gem += self.scores[vak]
        return gem / len(self.scores)
        
s = Student("John Doe", 20, "Gent")
s.add_score("Data Science", 15)
s.add_score("Data Analytics", 20)
print(s.aantal_vakken_geslaagd())
print(s.bereken_gemiddelde())

2
17.5


In [ ]:
# Oefening 3: Hoeveel studenten geslaagd voor een vak
def aantal_studenten_geslaagd(studentenlijst, vak):
    aantal = 0
    
    for student in studentenlijst:
        if vak in student.scores:
            if student.scores[vak] >= 10:
                aantal += 1
        
    return aantal


In [ ]:
# Oefening 4: Hoeveel studenten geslaagd voor elk vak
def aantal_student_geslaagd_per_vak(studentenlijst):
    # zoek alle vakken
    vakken = []
    for student in studentenlijst:
        for vak in student.scores:
            # if a student doesn't have a subject in their scores, but another student does
            if vak not in vakken:
                vakken.append(vak)
    for vak in vakken:
        geslaagd_per_vak[vak] = aantal_studenten_geslaagd(studentenlijst, vak)
    return geslaagd_per_vak
    # aantal studenten geslaagd per vak
aantal_studenten_geslaagd_per_vak(studentenlijst)

## Numpy Intro

De numpy libary of package is de kern van veel andere wiskundige rekentools for datamanagement of machine learning in python.
Het biedt onder andere een hoge performantie om te werken met rijen van meerdere dimensies en een reeks tools voor bewerkingen te doen met en op deze rijen.
* Een 1-dimensionale rij is een een normale rij
* Een 2-dimensionale rij is een matrix
* Een 3-dimensionale rij is bijvoorbeeld een RGB-figuur (derde dimensie bestaat uit drie elementen)

De standaard manier om deze package te gebruiken is door bovenaan je file de package te importeren met het commando:

In [19]:
import numpy as np

In [62]:
# Aanmaken arrays

# setting the seed to 100, will always generate the same random numbers
np.random.seed(100)

np.array([0,1,2,3,4,5])
np.array([[0,1,2], [3,4,5]])
# 10 rows and 5 columns
np.ones(shape=(10,5))
# instead of ones it's zeros
np.zeros(shape=(10, 5))
# eye will have ones diagonally
np.eye(10)
# will generate random 4 rows and 3 columns
np.random.random((4,3))
# gehele getallen random van 0 tot 100 en een size van 4 rijen en 3 kolommen
a = np.random.randint(100, size=(4,3))
print(a)
#-------------------------

# Bestuderen van de matrices

# get the third element from the second row
a[1, 2]

# get all values from top to bottom (the third element only)
a[:,2]

# get the values in a Z shape
a[1::2, ::2]
#-------------------------
# Bewerkingen met arrays
# element wise vermenigvuldiging (geen matrix vermenigvuldiging)
a*a
np.cos(a)
np.sin(a)
np.tan(a)
np.sqrt(a)
#-------------------------
# Vergelijken van rijen
# which elements are divisible by 2?
a % 2 == 0
# get all elements divisible by 2
a[a % 2 == 0]

#-------------------------
# Aggregate functies
a.sum()
a.mean()
np.median(a)

#-------------------------
# Copy arrays
b = a
# by reference and not by value!
b[0, 0] = -16

# by value!
b = a.copy()

#-------------------------
# Sort
a.sort(axis=1)
a

#-------------------------
# Indexing


#-------------------------
# Dimensies array manipuleren
# reshape into 3 rows and 4 columns
np.reshape(a, (3, 4))

#-------------------------
# Opslaan

#-------------------------

[[16  9 93]
 [86  2 27]
 [ 4 31  1]
 [13 83  4]]


array([[-16,   9,  93,   2],
       [ 27,  86,   1,   4],
       [ 31,   4,  13,  83]])

Maak nu de volgende oefeningen voor Numpy
* Maak 2 vierkante matrices met random waarden tussen 0 en 10. De ene is een 10x5 matrix, de andere is 5x10.
* Schrijf een functie die controleert of de dimensies van de matrices voldoen aan de voorwaarden voor matrixVermenigvuldiging
* Bereken de vermenigvuldiging van de matrix
* Toon de resultaten op alle even rijen
* Bereken de som van elke kolom
* Bereken het gemiddelde van de matrix
* Verander het type van de matrix naar een integer-type
* Toon alle rijen waar de 4e kolom een even getal bevat
* Wijzig de vorm van de matrix van een 10x10 naar een 5x20
* Bereken de getransponeerde matrix
* Bereken de vierkantswortel van elk element in deze matrix

In [86]:
import numpy as np

# Maak 2 vierkante matrices met random waarden tussen 0 en 10. De ene is een 10x5 matrix, de andere is 5x10.
first_array = np.random.randint(10, size=(10,5))
second_array = np.random.randint(10, size=(5,10))
#print(first_array)
#print("------------------")
#print(second_array)
#----------------------------------
# Schrijf een functie die controleert of de dimensies van de matrices voldoen aan de voorwaarden voor matrixVermenigvuldiging

# first matrix should have as many columns as the second matrix's rows
def check_if_able_to_multiply_matrices(first_matrix, second_matrix):
    #first_matrix_rows, first_matrix_columns = first_matrix.shape
    #second_matrix_rows, second_matrix_columns = second_matrix.shape
    first_matrix_columns = np.shape(first_matrix)[0]
    second_matrix_rows = np.shape(second_matrix)[1]
    if(first_matrix_columns == second_matrix_rows):
        return True
    return False

#print(check_if_able_to_multiply_matrices(first_array, second_array))
#-------------------------------------
# Bereken de vermenigvuldiging van de matrix
#print(np.dot(first_array, second_array))

#-------------------------------------
# Toon de resultaten op alle even rijen
first_array[first_array % 2 == 0]
second_array[second_array % 2 == 0]

#--------------------------------------
# Bereken de som van elke kolom
# axis = 0 means row and axis = 1 means columns
first_array_column_sums = first_array.sum(axis = 0)
# print(first_array_column_sums)

#-------------------------------------
# Bereken het gemiddelde van de matrix
print(np.mean(first_array))
print(np.mean(second_array))

#-----------------------------------------
# Verander het type van de matrix naar een integer-type
first_array.astype(int)
second_array.astype(int)

#------------------------------------------
# Toon alle rijen waar de 4e kolom een even getal bevat
first_array[first_array[:, 3] % 2 == 0]

#------------------------------------------

4.5
4.08


array([[1, 7, 4, 2, 4],
       [1, 2, 1, 8, 4],
       [4, 8, 6, 8, 9],
       [1, 6, 0, 4, 2]])

## Pandas Intro

Pandas is een open-source software library die is geschreven voor Python om aan data manipulatie en analyse te doen. 
Het biedt met name datastructuren aan voor het bewerken en manipuleren van numerieke tabellen en tijdreeksen. 
Pandas is uitermate geschikt voor tabulaire data uit bijvoorbeeld relationele databases of spreadsheets.
De API die aangeboden wordt door deze library kan je [hier](https://pandas.pydata.org/pandas-docs/stable/reference/index.html) vinden.

Deze library biedt mogelijkheden aan om een breed gamma van dataformaten in te lezen en weg te schrijven als dataframe, bijvoorbeeld: csv, xlsx, Json en SQL.
De basis van de libary is het concept van Series en Dataframes. 
Een Series is een soort lijst dat een aantal soorten data kan bevatten (numerieke waarden, datums, strings, ...). 
Een Dataframe aan de andere hand is een collectie van series met een gemeenschappelijke index.
Een series is dan gelijkaardig aan een kolom in een tabel en een dataframe de hele tabel.

Net zoals bij Numpy moet deze library geimporteerd worden voor we ermee kunnen werken.
Dit kan aan de hand van de volgende regel.

In [87]:
import pandas as pd

Nu ga ik eerst een voorbeeld tonen van het verschil van een Series en een Dataframe.

In [134]:
# Maak 2 series: auteurs en aantal boeken
auteurs = pd.Series(["GRR Martin", "Andy Weir", "Tolkien", "Isaac Asimov"])
n_books = pd.Series([7, 4, 20, 50])
print(auteurs)
print(n_books)

# Maak een dataframe aan voor deze 2 series
df = pd.DataFrame({"Auteurs": auteurs, "n_books": n_books})


# Voeg een serie toe met een geboortejaar (Laat er hier 1 ontbreken)
df["Geboortejaar"] = pd.Series([1950, 1960, 1970])
display(df)

0      GRR Martin
1       Andy Weir
2         Tolkien
3    Isaac Asimov
dtype: object
0     7
1     4
2    20
3    50
dtype: int64


Auteurs  n_books  Geboortejaar
0    GRR Martin        7        1950.0
1     Andy Weir        4        1960.0
2       Tolkien       20        1970.0
3  Isaac Asimov       50           NaN

Merk op dat in deze laatste toevoeging een geboortejaar ontbrak. Dit is echter geen probleem want ontbrekende data wordt default op Nan gezet. 
Deze Nan waarden zien iets waar we later bij data cleaning veel aandacht aan gaan besteden.

In [136]:
# set index
df.info()
df.describe()


df = df.set_index("Auteurs")

# we can use inplace=True parameter to overwrite the current df, we could have initialized it to df like above.
#df.reset_index("Auteurs", inplace=True)
display(df)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Auteurs       4 non-null      object 
 1   n_books       4 non-null      int64  
 2   Geboortejaar  3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


n_books  Geboortejaar
Auteurs                            
GRR Martin          7        1950.0
Andy Weir           4        1960.0
Tolkien            20        1970.0
Isaac Asimov       50           NaN

Voor de verdere bewerkingen maken we een random dataframe aan met 1000 rijen en 5 kolommen.

In [161]:
# random df
df2 = pd.DataFrame(np.random.random((1000, 5)))

# dimensions
len(df2)
df2.shape
df2.info()

# indexing
df2.iloc[500]
df.loc["Andy Weir", ["n_books", "Geboortejaar"]]
df2.head(10)
df2.tail(7)
df2.sample(n=10)
df2.sample(frac=0.01)
# will show values>0.5 from column 3
df2[df2[3]>0.5]

# drop columns, duplicates
# will delete column 3
df2.drop(3, axis=1)

#Reshaping data

#Handling null values
df = df.dropna(axis=0)
df2[5] = df2[0] * df2[1]

# changing the date to an int instead of a float
df["Geboortejaar"] = df["Geboortejaar"].astype(int)
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1000 non-null   float64
 1   1       1000 non-null   float64
 2   2       1000 non-null   float64
 3   3       1000 non-null   float64
 4   4       1000 non-null   float64
dtypes: float64(5)
memory usage: 39.2 KB


n_books  Geboortejaar
Auteurs                          
GRR Martin        7          1950
Andy Weir         4          1960
Tolkien          20          1970

Nu kan je het zelf oefenen met de volgende oefeningen:
* Maak een Series aan met 500 willekeurige continue getallen tussen 0 en 20
* Maak een Series aan met 500 willekeurige integer getallen tussen 40 en 200 (let erop dat het dtype van deze kolom correct is)
* Maak een Dataframe aan op basis van deze twee Series. De eerste is de "Lengte" en de tweede de "Breedte".
* Bereken nu de oppervlakte van elke rij en sla dit op in een nieuwe kolom
* Bereken de gemiddelde en mediaan van deze nieuwe kolom
* Voor de oppervlakte willen we niet met komma-getallen werken. Verander het type van deze kolom dus naar int
* Toon de breedte van alle rijen waarvoor de oppervlakte groter is dan het gemiddelde.
* Toon enkel de rijen waarvoor de breedte groter is dan de lengte

In [183]:
import pandas as pd
import numpy as np
# Maak een Series aan met 500 willekeurige continue getallen tussen 0 en 20
sr_willekeurige_getallen = pd.Series(np.random.randint(20, size=(500)))
print(sr_willekeurige_getallen)
#-----------------------------

# Maak een Series aan met 500 willekeurige integer getallen tussen 40 en 200 (let erop dat het dtype van deze kolom correct is)
sr_willekeurige_getallen_tussen_40_en_200 = pd.Series(np.random.randint(40,200, size=(500)))
print(sr_willekeurige_getallen_tussen_40_en_200)

#-------------------------------
# Maak een Dataframe aan op basis van deze twee Series. De eerste is de "Lengte" en de tweede de "Breedte".
df_obv_de_twee_series = pd.DataFrame({"Lengte": sr_willekeurige_getallen, "Breedte": sr_willekeurige_getallen_tussen_40_en_200})
display(df_obv_de_twee_series)
# -------------------------
# Bereken nu de oppervlakte van elke rij en sla dit op in een nieuwe kolom
sr_oppervlakte = pd.Series(df_obv_de_twee_series['Lengte'] * df_obv_de_twee_series['Breedte'])
pd.concat([df_obv_de_twee_series, sr_oppervlakte], axis=1)
#-------------------------------
# Bereken de gemiddelde en mediaan van deze nieuwe kolom
sr_oppverlakte_gem = sr_oppervlakte.mean()
sr_oppervlakte_mediaan = sr_oppervlakte.median()
print(sr_oppervlakte_mediaan)
#--------------------------------
# Voor de oppervlakte willen we niet met komma-getallen werken. Verander het type van deze kolom dus naar int


0      14
1       1
2       0
3      10
4      11
       ..
495     7
496    13
497     8
498    18
499    13
Length: 500, dtype: int32
0      172
1      116
2      115
3      160
4       63
      ... 
495    179
496     49
497    107
498    172
499    121
Length: 500, dtype: int32


Lengte  Breedte
0        14      172
1         1      116
2         0      115
3        10      160
4        11       63
..      ...      ...
495       7      179
496      13       49
497       8      107
498      18      172
499      13      121

[500 rows x 2 columns]

975.5
